  api:
    build: 
      context: ./gamification-api
      dockerfile: Dockerfile.dev  # Use the development Dockerfile
    container_name: gamification-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongodb:27017/gamification?authSource=admin
      - JWT_SECRET=your_jwt_secret_here
    volumes:
      - ./gamification-api:/app
      - /app/node_modules
    depends_on:
      - mongodb
    restart: unless-stopped